/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPaidAdvertisingRouteImport } from './routes/services.paid-advertising'
import { Route as ServicesContentCreationRouteImport } from './routes/services.content-creation'
import { Route as ServicesAutomationSystemsRouteImport } from './routes/services.automation-systems'
import { Route as ServicesAiReceptionistsRouteImport } from './routes/services.ai-receptionists'
import { Route as PackagesStarterRouteImport } from './routes/packages.starter'
import { Route as PackagesScaleRouteImport } from './routes/packages.scale'
import { Route as PackagesGrowthRouteImport } from './routes/packages.growth'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPaidAdvertisingRoute = ServicesPaidAdvertisingRouteImport.update({
  id: '/services/paid-advertising',
  path: '/services/paid-advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesContentCreationRoute = ServicesContentCreationRouteImport.update({
  id: '/services/content-creation',
  path: '/services/content-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAutomationSystemsRoute =
  ServicesAutomationSystemsRouteImport.update({
    id: '/services/automation-systems',
    path: '/services/automation-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAiReceptionistsRoute = ServicesAiReceptionistsRouteImport.update({
  id: '/services/ai-receptionists',
  path: '/services/ai-receptionists',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesStarterRoute = PackagesStarterRouteImport.update({
  id: '/packages/starter',
  path: '/packages/starter',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesScaleRoute = PackagesScaleRouteImport.update({
  id: '/packages/scale',
  path: '/packages/scale',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesGrowthRoute = PackagesGrowthRouteImport.update({
  id: '/packages/growth',
  path: '/packages/growth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/packages/growth': typeof PackagesGrowthRoute
  '/packages/scale': typeof PackagesScaleRoute
  '/packages/starter': typeof PackagesStarterRoute
  '/services/ai-receptionists': typeof ServicesAiReceptionistsRoute
  '/services/automation-systems': typeof ServicesAutomationSystemsRoute
  '/services/content-creation': typeof ServicesContentCreationRoute
  '/services/paid-advertising': typeof ServicesPaidAdvertisingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/packages/growth': typeof PackagesGrowthRoute
  '/packages/scale': typeof PackagesScaleRoute
  '/packages/starter': typeof PackagesStarterRoute
  '/services/ai-receptionists': typeof ServicesAiReceptionistsRoute
  '/services/automation-systems': typeof ServicesAutomationSystemsRoute
  '/services/content-creation': typeof ServicesContentCreationRoute
  '/services/paid-advertising': typeof ServicesPaidAdvertisingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/packages/growth': typeof PackagesGrowthRoute
  '/packages/scale': typeof PackagesScaleRoute
  '/packages/starter': typeof PackagesStarterRoute
  '/services/ai-receptionists': typeof ServicesAiReceptionistsRoute
  '/services/automation-systems': typeof ServicesAutomationSystemsRoute
  '/services/content-creation': typeof ServicesContentCreationRoute
  '/services/paid-advertising': typeof ServicesPaidAdvertisingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/demo'
    | '/packages/growth'
    | '/packages/scale'
    | '/packages/starter'
    | '/services/ai-receptionists'
    | '/services/automation-systems'
    | '/services/content-creation'
    | '/services/paid-advertising'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/demo'
    | '/packages/growth'
    | '/packages/scale'
    | '/packages/starter'
    | '/services/ai-receptionists'
    | '/services/automation-systems'
    | '/services/content-creation'
    | '/services/paid-advertising'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/demo'
    | '/packages/growth'
    | '/packages/scale'
    | '/packages/starter'
    | '/services/ai-receptionists'
    | '/services/automation-systems'
    | '/services/content-creation'
    | '/services/paid-advertising'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  PackagesGrowthRoute: typeof PackagesGrowthRoute
  PackagesScaleRoute: typeof PackagesScaleRoute
  PackagesStarterRoute: typeof PackagesStarterRoute
  ServicesAiReceptionistsRoute: typeof ServicesAiReceptionistsRoute
  ServicesAutomationSystemsRoute: typeof ServicesAutomationSystemsRoute
  ServicesContentCreationRoute: typeof ServicesContentCreationRoute
  ServicesPaidAdvertisingRoute: typeof ServicesPaidAdvertisingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/paid-advertising': {
      id: '/services/paid-advertising'
      path: '/services/paid-advertising'
      fullPath: '/services/paid-advertising'
      preLoaderRoute: typeof ServicesPaidAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/content-creation': {
      id: '/services/content-creation'
      path: '/services/content-creation'
      fullPath: '/services/content-creation'
      preLoaderRoute: typeof ServicesContentCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automation-systems': {
      id: '/services/automation-systems'
      path: '/services/automation-systems'
      fullPath: '/services/automation-systems'
      preLoaderRoute: typeof ServicesAutomationSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-receptionists': {
      id: '/services/ai-receptionists'
      path: '/services/ai-receptionists'
      fullPath: '/services/ai-receptionists'
      preLoaderRoute: typeof ServicesAiReceptionistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/starter': {
      id: '/packages/starter'
      path: '/packages/starter'
      fullPath: '/packages/starter'
      preLoaderRoute: typeof PackagesStarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/scale': {
      id: '/packages/scale'
      path: '/packages/scale'
      fullPath: '/packages/scale'
      preLoaderRoute: typeof PackagesScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/growth': {
      id: '/packages/growth'
      path: '/packages/growth'
      fullPath: '/packages/growth'
      preLoaderRoute: typeof PackagesGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  PackagesGrowthRoute: PackagesGrowthRoute,
  PackagesScaleRoute: PackagesScaleRoute,
  PackagesStarterRoute: PackagesStarterRoute,
  ServicesAiReceptionistsRoute: ServicesAiReceptionistsRoute,
  ServicesAutomationSystemsRoute: ServicesAutomationSystemsRoute,
  ServicesContentCreationRoute: ServicesContentCreationRoute,
  ServicesPaidAdvertisingRoute: ServicesPaidAdvertisingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
